<?php
/**
 * Template Name: Somos
 */

get_header(); ?>
<div id="primary" class="site-content">
    <div id="content" role="main">
        <div class="noticia-index somos clearfix">
            <div class="titulo-somos">
                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos_title.png" alt="titulo">
            </div>
            <article class="article-contenido-somos">
                <div class="texto-contenido">
                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/1.jpg" class="left">
                        <div class="texto right somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-r">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/nosotros.png">
                            </div>
                            <div class="texto-noticia-somos right">
                                Somos una Asociación de profesionales de la Industria Minera
                                con el objetivo de unir a todas las personas que conforman el
                                sector incluyendo metalurgia, geología y las ramas relacionadas,
                                con el fin de mejorar la formación profesional, impulsar las
                                Ciencias de la Tierra y luchar por el mejor desarrollo y eficiencia
                                de la industria minero-metalúrgica en Zacatecas
                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/2.jpg" class="right">
                        <div class="texto left somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-l">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/conocimientos.png">
                            </div>
                            <div class="texto-noticia-somos left">
                                Nuestra Asociación reúne el conocimiento
                                de la Metalurgia, capacitación, generación
                                de ideas e innovaciones.
                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/3.jpg" class="left">
                        <div class="texto right somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-r ">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/oportunidades.png">
                            </div>
                            <div class="texto-noticia-somos right">
                                A través de nuestra unión generamos
                                oportunidades de negocios para
                                fortalecer nuestro desarrollo y el de nuestra región.
                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/4.jpg" class="right">
                        <div class="texto left somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-l">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/comunicacion.png">
                            </div>
                            <div class="texto-noticia-somos left">
                                La toma de decisiones acertadas se basa en el
                                conocimiento, para lo cual creamos herramientas
                                electrónicas que permiten a nuestros socios
                                recibir información de valor en el momento
                                adecuado que ayudan a tomar mejores decisiones
                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/5.jpg" class="left">
                        <div class="texto right somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-r">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/quien_puede.png">
                            </div>
                            <div class="texto-noticia-somos right">
                                Todos los profesionistas relacionados
                                con la minería mexicana, sean mexicanos
                                u originarios de otro país que realicen
                                actividades mineras en otro país.
                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/6.jpg" class="right">
                        <div class="texto left somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-l">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/como-se-organiza.png">
                            </div>
                            <div class="texto-noticia-somos left">
                                La asociación de se organiza en Distritos,
                                que son los grupos de profesionales de las
                                ciencias de la tierra de las  unidades mineras
                                o localidades que se adhieren a la Asociación.
                                Tienen su Mesa Directiva propia. el mínimo de
                                socios para formar un distrito es de diez.

                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/7.jpg" class="left">
                        <div class="texto right somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-r">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/beneficios.png">
                            </div>
                            <div class="texto-noticia-somos right">
                                Premios Nacionales:
                                Se entregan desde 1975 y se otorgan de forma bianual en la
                                Convención de la Asociacioón. Son las distinciones a individuos
                                más importantes en el sector minero mexicanno, Cuyas categorías son:
                                Minería, Metalurgia, Geología, Educación en Ciencias de la tierra y
                                Medio Ambiente en la Minería.
                                <br>
                                Revista GEOMIMET: Como socio se recibe la revista de manera bimestral.
                                <br>
                                Para los socios del Distrito Zacatecas adicionalmente recibirán
                                nuestra revista electrónica Somos Mineros, la cual proporciona
                                información valiosa del acontecer Minero en Zacatecas, así como
                                de nuestros eventos y capacitaciones, contamos también con un
                                boletín semanal y nuestro perfil de facebook con el cual podrá
                                estar en contacto con los profesionales de la Industria de la región.
                                <br>
                                Actualización Profesional: A través de cursos y conferencias del
                                más alto nivel. Adhicionalmente se dispone de un programa de
                                capacitación a distancia con certificación en Canada gracias
                                al convenio con EduMine
                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/8.jpg" class="right">
                        <div class="texto left somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-l">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/otros-beneficios.png">
                            </div>
                            <div class="texto-noticia-somos left">
                                Fondo de defunción.  El socio tiene derecho a un
                                fondo de defunción con una suma asegurada de 100 mil pesos.
                                <br>
                                Precios preferenciales: Nuestros socios obtendrán
                                precios especiales en la Convención y las reuniones
                                organizadas en los distritos y publicaciones.
                            </div>
                        </div>
                    </div>

                    <div class="noticia-index somos clearfix">
                        <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/11.jpg" class="left">
                        <div class="texto right somos-txt">
                            <div class="subtitulo-noticia subtitulo-somos-r">
                                <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/somos/como-afiliarse.png">
                            </div>
                            <div class="texto-noticia-somos right">
                                <p>Llenar la forma de registro que podrás
                                descargar en el siguiente link:
                                </p>
                                <a href="http://www.geomin.com.mx/pdf/anuncios/SOLICITUDSOCIOS_AIMMGM.pdf">
                                    Descarga Formato
                                </a>
                                <p>
                                Enviar copia de título y/o cédula profesional
                                (credencial en caso de ser estudiante)
                                </p>
                                <p>
                                Realizar el pago correspondiente de acuerdo a la siguiente información:
                                </p>
                                <p>
                                    <strong>Inscripción socios nuevos  $50</strong>
                                </p>
                                <div class="table1 clearfix">
                                    <!--
                                    <div class="tr non clearfix">
                                        <div class="td1">
                                            Inscripción socios nuevos
                                        </div>
                                        <div class="td2">
                                            $50
                                        </div>
                                    </div>
                                    -->
                                    <div class="hr clearfix">
                                        <div class="td1">
                                            Tipo de socio
                                        </div>
                                        <div class="td2">
                                            Cuota anual
                                        </div>
                                    </div>
                                    <div class="tr non clearfix">
                                        <div class="td1">
                                            Socio
                                        </div>
                                        <div class="td2">
                                            $1,000
                                        </div>
                                    </div>
                                    <div class="tr non clearfix">
                                        <div class="td1">
                                            Socio honorario
                                        </div>
                                        <div class="td2">
                                            $500
                                        </div>
                                    </div>
                                    <div class="tr non clearfix">
                                        <div class="td1">
                                            Socio Profesor
                                        </div>
                                        <div class="td2">
                                            $500
                                        </div>
                                    </div>
                                    <div class="tr non clearfix">
                                        <div class="td1">
                                            Socio Estudiante
                                        </div>
                                        <div class="td2">
                                            $500
                                        </div>
                                    </div>
                                </div>
                                <p>
                                Realizar el depósito en:
                                </p>
                                <div class="txt-tab">
                                    <p>
                                    BBVA BANCOMER
                                        <br/>
                                    AIMMGM, A.C.-Oficina Central
                                        <br/>
                                    Cuenta 0153498530
                                        <br/>
                                    Clabe 012180001534985304
                                        <br/>
                                    </p>
                                </div>
                                <p>

                                Enviar la información a:
                                <div class="txt-tab">
                                    Anais Pineda
                                        <br/>
                                    Tel (55) 5543 9005 ext 106
                                        <br/>
                                    Fax (55) 5543 9005
                                    <br/>
                                    Correo  socios@aimmgm.org.mx
                                </div>
                                </p>
                            </div>
                        </div>
                    </div>

                </div>
            </article>
        </div>
    </div>
</div><!-- #content -->
</div><!-- #primary -->
<?php get_footer(); ?>